
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WrongInputException", targetNamespace = "http://server/")
public class WrongInputException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WrongInputException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WrongInputException_Exception(String message, WrongInputException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WrongInputException_Exception(String message, WrongInputException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.WrongInputException
     */
    public WrongInputException getFaultInfo() {
        return faultInfo;
    }

}
